### ISSUE TITLE
Input 1 width 399 does not match input 0 width 400

### ISSUE THREAD

**Issue by g-l-i-t-c-h-o-r-s-e** [HexCodeFFF/mediaforge#188] opened 2023-07-20 22:01 UTC
```$addaudio 1``` with an image and 8 minute long mp3 attached to the message

**Comment by HexCodeFFF** [comment] 2023-07-20 22:22
Please send the full traceback.txt

**Comment by g-l-i-t-c-h-o-r-s-e** [comment] 2023-07-20 23:19
> Please send the full traceback.txt

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/12114735/traceback.txt)

**Comment by HexCodeFFF** [comment] 2023-07-20 23:20
Duplicate of #129

**Closed by HexCodeFFF** 2023-07-20 23:20 UTC
Labels: bug
