### ISSUE TITLE
ffmpeg exits with no error message

### ISSUE THREAD

**Issue by lunaresss** [HexCodeFFF/mediaforge#164] opened 2023-03-26 05:32 UTC
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/11070857/traceback.txt)

**Comment by HexCodeFFF** [comment] 2023-03-26 06:50
For now I’m going to close this as a duplicate of #147 but it _might_ be it’s own issue, in that case it’s still a duplicate of #140 
If you can reliably reproduce this error _please_ tell me the steps/media

**Closed by HexCodeFFF** 2023-03-26 06:50 UTC
