### ISSUE TITLE
Command 'epicbirthday' raised an exception: NotImplementedError: 

### ISSUE THREAD

**Issue by panagiothspsall** [HexCodeFFF/mediaforge#186] opened 2023-07-05 11:31 UTC
DATETIME:2023-07-05 06:29:33.122309
COMMAND:
TRACEBACK:
Traceback (most recent call last):
  File "C:\Users\minec\AppData\Local\pypoetry\Cache\virtualenvs\mediaforge-Vm0vmKVg-py3.11\Lib\site-packages\discord\app_commands\commands.py", line 841, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minec\PycharmProjects\captionbot\src\commands\image.py", line 128, in epicbirthday
    await process(ctx, processing.ffmpeg.epicbirthday, [], text)
  File "C:\Users\minec\PycharmProjects\captionbot\src\core\process.py", line 157, in process
    raise e
  File "C:\Users\minec\PycharmProjects\captionbot\src\core\process.py", line 125, in process
    result = await run()
             ^^^^^^^^^^^
  File "C:\Users\minec\PycharmProjects\captionbot\src\core\process.py", line 108, in run
    command_result = await func(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minec\PycharmProjects\captionbot\src\processing\ffmpeg.py", line 894, in epicbirthday
    raise NotImplementedError
NotImplementedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\minec\AppData\Local\pypoetry\Cache\virtualenvs\mediaforge-Vm0vmKVg-py3.11\Lib\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minec\AppData\Local\pypoetry\Cache\virtualenvs\mediaforge-Vm0vmKVg-py3.11\Lib\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'epicbirthday' raised an exception: NotImplementedError:

**Comment by HexCodeFFF** [comment] 2023-07-05 11:34
Duplicate of #132

**Closed** 2023-07-05 11:34 UTC
Labels: duplicate
