### ISSUE TITLE
processing.common.CMDError: Command raised an exception

### ISSUE THREAD

**Issue by idomanteu** [HexCodeFFF/mediaforge#196] opened 2023-07-31 17:38 UTC
processing.common.CMDError: Command raised an exception: CMDError: Command ('ffmpeg', '-i', '/dev/shm/mediaforge/WiMDsyFh.png', '-i', '/dev/shm/mediaforge/snVUtzwa.gif', '-filter_complex', '[0]format=pix_fmts=yuva420p[0f];[1]format=pix_fmts=yuva420p[1f];[0f][1f]vstack=inputs=2', '-c:v', 'png', '-fs', '1G', '-fps_mode', 'vfr', '/dev/shm/mediaforge/ebzXPXMt.mp4') failed.

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/12217712/traceback.txt)

**Comment by HexCodeFFF** [comment] 2023-08-06 04:09
Duplicate of #147

**Closed by HexCodeFFF** 2023-08-06 04:09 UTC
