### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by RonRed283** [HexCodeFFF/mediaforge#51] opened 2022-01-02 10:59 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Traceback**
If the bot uploaded a txt file with the error, please upload it here.

**Additional context**

**Comment by HexCodeFFF** [comment] 2022-01-02 11:00
Duplicate of #50

**Closed** 2022-01-02 11:00 UTC
Labels: bug, duplicate
