### ISSUE TITLE
cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by AshleyUwUwU** [HexCodeFFF/mediaforge#211] opened 2023-09-23 11:52 UTC
### Describe the bug

Video wont download

### Traceback

[traceback 3.txt](https://github.com/HexCodeFFF/mediaforge/files/12706351/traceback.3.txt)

**Comment by HexCodeFFF** [comment] 2023-09-23 23:17
Duplicate of #209

**Closed by HexCodeFFF** 2023-09-23 23:17 UTC
Labels: bug
