### ISSUE TITLE
Tenor API: asyncio.TimeoutError

### ISSUE THREAD

**Issue by BandBoxBrawl** [HexCodeFFF/mediaforge#216] opened 2023-10-27 21:46 UTC
### Describe the bug

Upon attempting a $motivate, the bot attempts to download for five-ish minutes before providing an error, stating: **Your command encountered an error due to limited resources on the server.**

### Traceback

```
DATETIME:2023-10-27 21:42:38.392034
COMMAND:$motivate Me when dinner ready : ) 
(I'm a hungry boy, this is my pre-dinner celebration dance)
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/caption.py", line 30, in motivate
    await process(ctx, processing.ffmpeg.motivate, [["VIDEO", "GIF", "IMAGE"]], caption)
  File "/mediaforge/src/core/process.py", line 151, in process
    raise e
  File "/mediaforge/src/core/process.py", line 62, in process
    urls = await imagesearch(ctx, len(inputs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/utils/scandiscord.py", line 78, in imagesearch
    hm = await handlemessagesave(m)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/utils/scandiscord.py", line 35, in handlemessagesave
    tenor = await fetch(
            ^^^^^^^^^^^^
  File "/mediaforge/src/utils/common.py", line 17, in fetch
    async with session.get(url) as response:
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/aiohttp/client.py", line 493, in _request
    with timer:
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/aiohttp/helpers.py", line 725, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```

**Comment by HexCodeFFF** [comment] 2023-10-28 19:59
Ok I increased the timeout to 10 minutes, this is a band-aid solution but it should *hopefully* fix it. I was unable to reproduce the behavior outside of MediaForge even inside it's docker container so i dont think it's my ip being blocked or my code being wrong, i think its just mediaforge being overloaded.

**Comment by HexCodeFFF** [comment] 2023-10-28 20:17
seems to have worked, so ill close this for now. feel free to re-open if the issue happens again

**Closed by HexCodeFFF** 2023-10-28 20:17 UTC
Labels: bug
