### ISSUE TITLE
Command 'breakingnews' raised an exception: NotImplementedError: 

### ISSUE THREAD

**Issue by SlovakianMapper** [HexCodeFFF/mediaforge#213] opened 2023-09-26 14:39 UTC
### Describe the bug

Upon executing the command /breakingnews, it outputs an error and doesn't run.

### Traceback

DATETIME:2023-09-26 14:31:12.710259
COMMAND:/breakingnews {'caption': 'test'}
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/caption.py", line 87, in breakingnews
    raise NotImplementedError  # TODO: implement
    ^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'breakingnews' raised an exception: NotImplementedError: 

### Expected Behavior

I expected the command to generate an image.

### Steps To Reproduce

Run the command /breakingnews <text>.

**Comment by HexCodeFFF** [comment] 2023-10-28 20:17
duplicate of #133

**Closed by HexCodeFFF** 2023-10-28 20:17 UTC
Labels: bug
