### ISSUE TITLE
Command ('ffmpeg', '-i', 'temp/wNlzrWKp.mp4', '-i', 'temp/IVpawNJX.wav', '-c:v', 'copy', '-c:a', 'copy', '-map', '0:v:0', '-map', '1:a:0', 'temp/CWdfjrvf.mp4') failed.

### ISSUE THREAD

**Issue by yacinebomb** [HexCodeFFF/mediaforge#77] opened 2022-03-15 16:40 UTC
**Describe the bug**
Everytime i try to use the $autotune command, each time making sure that parameters are properly set (i.e. at values that they accept), Mediaforge returns with this error.

**Screenshots**
[CDE17F96-0339-42AC-B323-7B16E5E5C27A](https://user-images.githubusercontent.com/101659417/158427431-2652cde5-d69f-4e7d-89f6-ca4e325f137d.jpeg)
**Traceback**
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/8255419/traceback.txt)

**Comment by HexCodeFFF** [comment] 2022-03-15 20:25
Doesn't have anything to do with your parameters, it's just a dumb mistake I made when I naively replaced "aac" from all ffmpeg calls to "copy", it's trying to copy a wav file into a video which it obviously can't do

Should be easy to fix.

**Comment by HexCodeFFF** [comment] 2022-03-19 23:54
duplicate of #75

**Closed by HexCodeFFF** 2022-03-19 23:54 UTC
Labels: bug
