### ISSUE TITLE
ffmpeg: Error muxing a packet

### ISSUE THREAD

**Issue by TheVisual** [HexCodeFFF/mediaforge#181] opened 2023-06-11 00:14 UTC
[traceback (1).txt](https://github.com/HexCodeFFF/mediaforge/files/11713561/traceback.1.txt)

https://github.com/HexCodeFFF/mediaforge/assets/132447890/940537b0-f941-402d-8b01-98ab249a298b

**Comment by HexCodeFFF** [comment] 2023-07-19 04:20
Duplicate of #178

**Closed** 2023-07-19 04:20 UTC
Labels: bug, duplicate, external issue
