### ISSUE TITLE
cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by Taoball0** [HexCodeFFF/mediaforge#212] opened 2023-09-25 06:14 UTC
### Describe the bug

I couldnt download a video called: vsc verified ong (Lebrun James and basketmball aproved)

### Traceback

https://cdn.discordapp.com/attachments/1121531893398110343/1155747879282016326/traceback.txt

**Comment by HexCodeFFF** [comment] 2023-09-25 15:52
Duplicate of #209

**Closed by HexCodeFFF** 2023-09-25 15:52 UTC
Labels: bug
