### ISSUE TITLE
Slash commands

### ISSUE THREAD

**Issue by longjumping** [HexCodeFFF/mediaforge#118] opened 2022-09-02 03:13 UTC
### Describe the feature you'd like

title

**Comment by HexCodeFFF** [comment] 2022-09-02 03:14
I plan on migrating to these at some point but I’m more focused on making the bot like remotely stable first

**Comment by HexCodeFFF** [comment] 2022-09-02 03:15
Wait
Duplicate of #93 lmao

**Closed by HexCodeFFF** 2022-09-02 03:15 UTC
Labels: suggestion, low priority
