### ISSUE TITLE
cant convert mp4 to gif

### ISSUE THREAD

**Issue by EthanMixab** [HexCodeFFF/mediaforge#127] opened 2022-11-22 04:26 UTC
### Describe the bug

discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'togif' raised an exception: ReturnedNothing: Expected image, <function mp4togif at 0x7f9399168360> returned nothing.

### Traceback

DATETIME:2022-11-22 04:24:25.355202
COMMAND:
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/conversion.py", line 139, in togif
    await process(ctx, processing.ffmpeg.mp4togif, [["VIDEO"]])
  File "/mediaforge/src/core/process.py", line 147, in process
    raise e
  File "/mediaforge/src/core/process.py", line 128, in process
    raise processing.common.ReturnedNothing(f"Expected image, {func} returned nothing.")
processing.common.ReturnedNothing: Expected image, <function mp4togif at 0x7f9399168360> returned nothing.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'togif' raised an exception: ReturnedNothing: Expected image, <function mp4togif at 0x7f9399168360> returned nothing.

The above exception was the direct cause of the following exception:

discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'togif' raised an exception: ReturnedNothing: Expected image, <function mp4togif at 0x7f9399168360> returned nothing.

### Expected Behavior

convert mp4 to gif

### Anything Else

I put 
/togif https://cdn.discordapp.com/attachments/1040423769254141973/1043758568316350524/trim.06CFFC1C-3418-4C10-8C35-7C0984C71D99.mov

it doesnt work

**Comment by HexCodeFFF** [comment] 2022-11-22 04:30
duplicate of #126 and I still can't reliably reproduce.

**Closed by HexCodeFFF** 2022-11-22 04:30 UTC
Labels: bug
