### ISSUE TITLE
Command 'breakingnews' raised an exception: NotImplementedError: 

### ISSUE THREAD

**Issue by juanroman74454811** [HexCodeFFF/mediaforge#175] opened 2023-05-18 14:21 UTC
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/11508534/traceback.txt)
fix this please i was in MyKHchu Server and i wanna use the breaking news command but the bot said "fuck you" to me pls help, THE COMMANDS BROKEN

**Comment by HexCodeFFF** [comment] 2023-05-18 14:22
Duplicate of #133

**Closed** 2023-05-18 14:22 UTC
Labels: duplicate, not a bug
