### ISSUE TITLE
expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by EMHMED123** [HexCodeFFF/mediaforge#74] opened 2022-03-08 22:26 UTC
[traceback-1.txt](https://github.com/HexCodeFFF/mediaforge/files/8210050/traceback-1.txt)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Traceback**
If the bot uploaded a txt file with the error, please upload it here.

**Additional context**

**Comment by HexCodeFFF** [comment] 2022-03-08 22:34
Hmm, I'll have to give this a look

**Comment by HexCodeFFF** [comment] 2022-03-20 00:35
duplicate of #72

**Closed by HexCodeFFF** 2022-03-20 00:35 UTC
Labels: bug
