### ISSUE TITLE
404 Not Found (error code: 10008): Unknown Message

### ISSUE THREAD

**Issue by Natus193** [HexCodeFFF/mediaforge#198] opened 2023-08-01 05:15 UTC
<:eemark:803791399710883871> `discord.errors.NotFound: Command raised an exception: NotFound: 404 Not Found (error code: 10008): Unknown Message`

**Comment by HexCodeFFF** [comment] 2023-08-06 04:07
Duplicate of #197

**Closed by HexCodeFFF** 2023-08-06 04:07 UTC
