### ISSUE TITLE
Add 'speech bubble' (with optional export as GIF for Discord favorites storage)

### ISSUE THREAD

**Issue by dfault-user** [HexCodeFFF/mediaforge#116] opened 2022-08-14 17:11 UTC
### Describe the feature you'd like

It's right on the tin. Multiple speech bubbles should also be available to be overlayed on the top, or even bottom, of an image.

**Comment by HexCodeFFF** [comment] 2022-08-14 17:13
Duplicate of #83

**Closed** 2022-08-14 17:13 UTC
Labels: duplicate, suggestion
