### ISSUE TITLE
cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by twcpa** [HexCodeFFF/mediaforge#210] opened 2023-09-23 04:07 UTC
### Describe the bug

Trying to download:
https://youtu.be/jU7GOJtpGek
results in an error:
"TypeError: Command raised an exception: TypeError: cannot pickle '_io.BufferedReader' object"

### Traceback

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/12705570/traceback.txt)

### Expected Behavior

The bot would send the video that I requested it to download

### Steps To Reproduce

Type and send "$videodl https://youtu.be/jU7GOJtpGek" in any Discord server that has MediaForge

**Comment by HexCodeFFF** [comment] 2023-09-23 23:17
Duplicate of #209

**Closed by HexCodeFFF** 2023-09-23 23:17 UTC
Labels: bug
