### ISSUE TITLE
Command 'breakingnews' raised an exception: NotImplementedError: 

### ISSUE THREAD

**Issue by Coolgithubuser9** [HexCodeFFF/mediaforge#153] opened 2023-01-23 18:28 UTC
this is what it has say | DATETIME:2023-01-23 18:25:21.901102
COMMAND:
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/caption.py", line 87, in breakingnews
    raise NotImplementedError  # TODO: implement
    ^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'breakingnews' raised an exception: NotImplementedError:

**Comment by HexCodeFFF** [comment] 2023-01-23 18:29
Duplicate of #133

**Closed by HexCodeFFF** 2023-01-23 18:29 UTC
