### ISSUE TITLE
cant convert video to gif 

### ISSUE THREAD

**Issue by EthanMixab** [HexCodeFFF/mediaforge#126] opened 2022-11-22 04:01 UTC
### Describe the bug

discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'togif' raised an exception: ReturnedNothing: Expected image, <function mp4togif at 0x7f9399168360> returned nothing.

### Traceback

DATETIME:2022-11-22 03:59:07.555504
COMMAND:
TRACEBACK:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 861, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/conversion.py", line 139, in togif
    await process(ctx, processing.ffmpeg.mp4togif, [["VIDEO"]])
  File "/mediaforge/src/core/process.py", line 147, in process
    raise e
  File "/mediaforge/src/core/process.py", line 128, in process
    raise processing.common.ReturnedNothing(f"Expected image, {func} returned nothing.")
processing.common.ReturnedNothing: Expected image, <function mp4togif at 0x7f9399168360> returned nothing.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/app_commands/commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'togif' raised an exception: ReturnedNothing: Expected image, <function mp4togif at 0x7f9399168360> returned nothing.

The above exception was the direct cause of the following exception:

discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'togif' raised an exception: ReturnedNothing: Expected image, <function mp4togif at 0x7f9399168360> returned nothing.

### Expected Behavior

It was supposed to convert my video to a gif

**Comment by HexCodeFFF** [comment] 2022-11-22 04:02
Hmm that’s weird. Can you upload the mp4 that you tried to convert?

**Comment by EthanMixab** [comment] 2022-11-22 04:03
> Hmm that’s weird. Can you upload the mp4 that you tried to convert?

https://cdn.discordapp.com/attachments/1040423769254141973/1043758715855179836/video0_8.mov

**Comment by HexCodeFFF** [comment] 2022-11-22 04:21
It's converting to a gif just fine for me. I do see the error in the logs but unfortunately, without being able to reliably reproduce it I can't fix the bug since I don't know what caused it

**Comment by HexCodeFFF** [comment] 2022-11-22 04:22
I'm gonna close the issue for now. If you can reliably get the error to occur, please re-open the issue with the steps you took to do so.

**Closed by HexCodeFFF** 2022-11-22 04:22 UTC
Labels: bug, unable to reproduce
