### ISSUE TITLE
Command 'epicbirthday' raised an exception: NotImplementedError: 

### ISSUE THREAD

**Issue by a-turtle9302** [HexCodeFFF/mediaforge#176] opened 2023-05-20 17:04 UTC
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/11522818/traceback.txt)

**Comment by HexCodeFFF** [comment] 2023-05-20 17:58
Duplicate of #132

**Closed** 2023-05-20 17:59 UTC
Labels: duplicate, not a bug
